### ISSUE TITLE
Opera Mobile

### ISSUE THREAD

**Issue by MacKenzieRose** [MissMadore/ecommerce-pattern-library#12]
Hi lovely,

Site is super clean! The only thing I caught comes from your privacy policy page, where there's some weirdness with the page width on mobile portrait mode (there's a horizontal overflow) and some of the links look a little weird (like content is missing/covered):

![IMG_0625](https://user-images.githubusercontent.com/19557909/79604266-c32d7f80-80bb-11ea-859d-8c5f9a5bcef4.png)

**Comment by MissMadore** [comment]
Oh damn! I might wrap the whole thing in a card div to help keep it on the page. @thomasjbradley could you advise?

**Comment by MacKenzieRose** [comment]
I honestly don't know if we're allowed to add any html content (divs with grids/units? typografier classes?) to the file or not, or if we just drop the content in, and hope for the best 😆 Looking forward to the answer, since it looks like everyone has approached these a little differently.

**Comment by MissMadore** [comment]
I ended up throwing mine into a div that had the island class on it to pull the content away from the edges, I'm not sure what produces the overflow behavior on mobile though

**Comment by MacKenzieRose** [comment]
I have a lab 5–7 today; if you tag me with requests, I can test it then for you :)

**Comment by MissMadore** [comment]
@thomasjbradley

It appears that it's being caused by the links in the ul of the content. I'm not sure how to address this.

**Comment by MacKenzieRose** [comment]
is everything pushed to github? I can try and troubleshoot it from here :)

**Comment by MacKenzieRose** [comment]
Upon closer inspection of this instance in other pattern library code (including my own), it looks like the urls always cause a horizontal scroll at some point; yours happens almost exactly at 320 pixels, so in my not-so-professional opinion, I vote ignore it.

The only way I can see addressing it is to make the font size smaller (so it will break at a smaller width), which introduces other accessibility issues.

**Comment by MissMadore** [comment]
I think I will elect to ignore it as a lesser of many evils. So long as on mobile you are still able to scroll over horizontally to see the link information, I'll take that as a higher priority than aesthetics!

Thank you for your help!

**Comment by thomasjbradley** [comment]
I would be okay with you adding some `overflow-x: hidden` to the `body` tag inside `theme.css` to prevent the horizontal scrolling.

**Comment by MissMadore** [comment]
In this case do I need to manually add a body tag somewhere 😰 @thomasjbradley

**Comment by thomasjbradley** [comment]
Nope. It’s in the `default.html` layout. Just need to style it.
