### ISSUE TITLE
Microsoft Edge

### ISSUE THREAD

**Issue by HannahDelaney** [MissMadore/ecommerce-pattern-library#14]
Hey! Great site, the gradients are cool, especially on hover.

My only comments on your homepage would be that the line-length of the banner is a bit long, and you could make it even stronger by adding skip-links in.

Well done!

@thomasjbradley

**Comment by MissMadore** [comment]
Line length of the banner is all fixed up! Oh yeah.. skip links 😨

**Comment by MissMadore** [comment]
Added up! Thank you for the reminder
