### ISSUE TITLE
Final Grade

### ISSUE THREAD

**Issue by MissMadore** [MissMadore/ecommerce-pattern-library#15]
@thomasjbradley

Please accept my Request for Grade for the ecommerce pattern library: Tits & Silence.

My pattern library for Tits & Silence in its present form successfully covers all reasonable additions to the structure of the website. In the weeks before submission, some minor changes and additions needed to be made with respect to function of forms and the inclusion of a banner. I concede that I was not entirely prepared for the banner element of the surprise pages, but was able to resolve the missing component very quickly and without much change to my initial patterns. My one truly significant missed element was the inclusion of skip links for accessibility purposes. 

With regards to the documentation of my pattern library, I feel that it is concise, straightforward, and flexible for use if another individual is tasked with creating a page with only the pattern library as a resource. As we did not do this component of the product, I can't say with absolute certainty, but I ensured that included descriptions were as precise as possible for the application of each pattern. 

The project's pages, including the template and surprise pages, have all been successfully completed and linked throughout my completed site. Although there was not time to complete additional pages (such as the artist list) I made an effort to give the impression of a full site by including extra elements that I hope will at least make you chuckle. In this way, all links throughout the site will inevitably lead you somewhere.

This project was a tremendously fun challenge to tackle, and has added a layer of ease to creating full looking websites as a part of my skillset. I'm really happy that we got to learn to do this, and it was well worth the stress of having a single project to tend to over the course of the term. 

All this being said, I feel that the missed elements in my pattern library revealed during user testing may merit the loss of a half mark off under patterns, and a half mark under accessibility per the provided rubric. 

I would love to request an A+ for this work, as I am incredibly proud of how it turned out, but would also realistically accept an A for these missed elements if they resulted in full point deductions from the rubric. 

It has been supremely fun learning now to do this, and I hope you are just as proud of my final product as I am! :shipit: 

---

*Style & design* — **3**
She's beautiful and there is a cohesive theme running through the design of the pages. I love that I got to make the gradient text work!

*Patterns* — **2.5**
Missing out on the banner for the surprise page was a loss, but it was very easily and quickly rectified.

*Explanations* — **3**
Everything is complete, clear, and concise as was possible. 

*Accessibility* — **2.5**
Missed out on adding skip links, but the rest of the content is very much accessible!

*Semantics* — **3**
Well structured work with straightforward use of the coding tools we have learned so far. 

*Responsiveness* — **3**
Pages reflow and resize well with the use of a grid system.

*Code quality* — **3**
All indentation rules were followed and tags used where appropriate

*Git & commits* — **3**
Killer commit messages in my opinion, and I was much more in the habit of checking in components as they were finished so it was easier to track changes during this project. 

---

23/24 — **96%**

**Comment by thomasjbradley** [comment]
The website turned out nicely—I love the simplicity of the design mixed with the single gradient. Thank you for putting in the effort & applying the materials this term.
