### ISSUE TITLE
Grade Request: Completed Week 10 Preparing Product Data

### ISSUE THREAD

**Issue by MissMadore** [MissMadore/ecommerce-pattern-library#3]
Hey @thomasjbradley
Followed the lesson and got through creating a bunch of .md files. I'm waiting on more artworks from friends, but I have 7 products for now to populate with. Moving on to the next lesson! The pages themselves look a little nutty because the images don't have a container to conform to, but at least they're all showing up

**Comment by thomasjbradley** [comment]
👍
