### ISSUE TITLE
Grade request: Jekyll Generator Week 10

### ISSUE THREAD

**Issue by MissMadore** [MissMadore/ecommerce-pattern-library#4]
@thomasjbradley I've completed Week 10's Jekyll Generator, but would like to try and get my button text to appear smaller. Is there a way to define a custom class on the button if it's just being {% placed like this %}?

**Comment by MissMadore** [comment]
Oh wait never mind I just solved it by putting the {% button %} into a div with the text size class applied there! 👍

**Comment by MissMadore** [comment]
ALSO: Here's the Markdown Manipulator Quiz @thomasjbradley

<img width="736" alt="Screen Shot 2020-03-24 at 4 52 49 PM" src="https://user-images.githubusercontent.com/43224886/77475909-f0a24880-6def-11ea-9620-5cc16e41e972.png">

**Comment by thomasjbradley** [comment]
What page can I see the ”Jekyll generators”? Did you commit & push?

**Comment by MissMadore** [comment]
Whoops! Definitely forgot to push, it should be there now @thomasjbradley

**Comment by thomasjbradley** [comment]
🥇
