### ISSUE TITLE
Tasks Completed: Homepage Template & Product List Page Template & Product Detail Page Template

### ISSUE THREAD

**Issue by MissMadore** [MissMadore/ecommerce-pattern-library#5]
Hi @thomasjbradley I've completed my homepage, product list, and product details pages ! I was able to add the work of a few of my friends and the product list is looking much more robust now 👍

**Comment by MissMadore** [comment]
<img width="959" alt="Screen Shot 2020-04-13 at 9 03 45 PM" src="https://user-images.githubusercontent.com/43224886/79174959-515aea80-7dca-11ea-9e10-5232e695e498.png">

**Comment by MissMadore** [comment]
Also, got YAML Yodeller completed!

**Comment by thomasjbradley** [comment]
:shipit:
