### ISSUE TITLE
Question & Task Complete: Checkout Form Page Template

### ISSUE THREAD

**Issue by MissMadore** [MissMadore/ecommerce-pattern-library#6]
Hi @thomasjbradley

I've finished building my checkout page, and aesthetically it has all the components as loosely outlined in my wireframe. 

However, because two sections of the form are split between two cards, and my inputs as they stand are not surrounded by form tags, would my button on the payment card in theory be able to trigger the submission of both cards' inputs? Could you advise on how best to structure the form functionality?

**Comment by thomasjbradley** [comment]
What about just changing the `<div>` tag to be a `<form>` tag?
https://github.com/MissMadore/ecommerce-pattern-library/blob/master/checkout.html#L6

**Comment by MissMadore** [comment]
Would that still work with forms spread across the two final cards?

**Comment by thomasjbradley** [comment]
Tots def.

**Comment by MissMadore** [comment]
Okay sick! I will give it a shot 👍

**Comment by MissMadore** [comment]
All formatted and linked up!
