### ISSUE TITLE
Task Complete: Surprise Page #1, Surprise Page#2, Finalizing Pattern Docs

### ISSUE THREAD

**Issue by MissMadore** [MissMadore/ecommerce-pattern-library#7]
Hi @thomasjbradley

I've completed the first surprise page, the only modification made was to apply my default layout and to add a div surrounding the content with the class "island" to pull the content away from the edges of the page. 

Also completed is the second surprise page. And my pattern library documentation is complete!

**Comment by thomasjbradley** [comment]
`content` isn’t really the best name for that page, maybe `terms`?

**Comment by thomasjbradley** [comment]
I don’t see a `README.md` for the documentation finalizing.

**Comment by MissMadore** [comment]
Oh! Gotcha, I just pulled the html file provided with the surprise page document straight into my pattern library. Will change right away!

**Comment by MissMadore** [comment]
> I don’t see a `README.md` for the documentation finalizing.

I will have to go find in the lessons the correct way to do that up!

**Comment by MissMadore** [comment]
@thomasjbradley Please find my README.md file included in my files as part of the last commit pushed in! Pattern Docs Finalized :shipit: 

content.html has also been changed!

**Comment by thomasjbradley** [comment]
🌈
